import logging
import os
import re
import time

from groq import Groq

logger = logging.getLogger(__name__)

MODEL = os.environ.get("GROQ_TEXT_MODEL", "llama-3.1-8b-instant")

# llama-3.1-8b-instant is rate-limited to 6000 tokens/minute on the on-demand tier.
# Keep prompt + completion comfortably under that so we never hit a 413 again.
MAX_PROMPT_TOKENS = int(os.environ.get("GROQ_MAX_PROMPT_TOKENS", "4200"))
MAX_COMPLETION_TOKENS = int(os.environ.get("GROQ_MAX_COMPLETION_TOKENS", "900"))
MAX_CONTEXT_CHUNKS = int(os.environ.get("RAG_MAX_CONTEXT_CHUNKS", "8"))
MAX_CHARS_PER_CHUNK = int(os.environ.get("RAG_MAX_CHARS_PER_CHUNK", "900"))


def is_valid_api_key() -> bool:
    api_key = os.environ.get("GROQ_API_KEY", "").strip()
    return bool(api_key and len(api_key) >= 20 and not api_key.lower().startswith("your_"))


def get_client():
    return Groq(api_key=os.environ["GROQ_API_KEY"].strip(), timeout=30.0)


def estimate_tokens(text: str) -> int:
    # Rough but reliable-enough heuristic (~4 chars/token for English prose).
    return max(1, len(text) // 4)


def _select_and_trim_chunks(context_chunks: list, max_chunks: int, max_chars_per_chunk: int, token_budget: int) -> list:
    """Pick strong chunks while keeping room for multiple documents.

    Key fix: summary chunks are generated by an LLM and may mention a different
    company/document name (e.g. a summary of Company_report.pdf might say 'Zephyr
    Consulting' if the document mentions that company). To prevent the LLM from
    citing the wrong company name, we always prefer direct parsed text chunks over
    summary chunks for the same document. Summaries are only used when a document
    has NO direct text chunks in the candidate set.
    """
    # Separate direct-parse (raw text) chunks from summary chunks per document
    direct_by_doc: dict = {}
    summary_by_doc: dict = {}
    for chunk in context_chunks:
        doc_id = chunk.get("document_id") or chunk.get("filename")
        if chunk.get("content_type") == "summary" or "summary-fallback" in (chunk.get("matched_by") or []):
            summary_by_doc.setdefault(doc_id, []).append(chunk)
        else:
            direct_by_doc.setdefault(doc_id, []).append(chunk)

    all_doc_ids = list(dict.fromkeys(
        (chunk.get("document_id") or chunk.get("filename")) for chunk in context_chunks
    ))

    ordered = []
    for doc_id in all_doc_ids:
        # Prefer direct chunks; only fall back to summary if no direct chunks exist
        candidates = direct_by_doc.get(doc_id) or summary_by_doc.get(doc_id) or []
        if candidates:
            ordered.append(candidates[0])  # best (already ranked) chunk for this doc
        if len(ordered) >= max_chunks:
            break

    # Fill remaining slots round-robin across documents (not flat rank
    # order), so the per-doc balance built above isn't undone by always
    # grabbing the next-best chunk from whichever doc already ranks highest.
    remaining_by_doc = {
        doc_id: [c for c in direct_by_doc.get(doc_id, []) if c not in ordered]
        for doc_id in all_doc_ids
    }
    round_idx = 0
    while len(ordered) < max_chunks and any(remaining_by_doc.values()):
        for doc_id in all_doc_ids:
            queue = remaining_by_doc.get(doc_id) or []
            if round_idx < len(queue):
                ordered.append(queue[round_idx])
                if len(ordered) >= max_chunks:
                    break
        round_idx += 1

    selected = []
    running_tokens = 0
    for chunk in ordered:
        text_content = (chunk.get("text_content") or "")[:max_chars_per_chunk]
        chunk_tokens = estimate_tokens(text_content) + 30
        if running_tokens + chunk_tokens > token_budget and selected:
            break
        trimmed = dict(chunk)
        trimmed["text_content"] = text_content
        selected.append(trimmed)
        running_tokens += chunk_tokens
    return selected


def generate_rag_response(query: str, context_chunks: list, chat_history: list = None) -> str:
    if not context_chunks:
        return "I couldn't find anything in your documents that's relevant to that. Try rephrasing, or check you've selected the right document/folder scope."

    if not is_valid_api_key():
        fallback_ans = "[Mode: Local Simulation (No valid GROQ_API_KEY set)]\n\nHere are matching extracts from your documents:\n\n"
        for chunk in context_chunks[:MAX_CONTEXT_CHUNKS]:
            filename = chunk.get("filename", "Unknown")
            page_num = chunk.get("page_number", 1)
            content_type = chunk.get("content_type", "text")
            snippet = (chunk.get("text_content") or "")[:220].replace("\n", " ")
            fallback_ans += f"- {content_type.title()} from **{filename}** (Page {page_num}): \"{snippet}...\" [{filename}, Page {page_num}]\n"
        return fallback_ans

    # Reserve budget for instructions/query, give the rest to source context.
    instruction_overhead_tokens = 350
    context_token_budget = max(500, MAX_PROMPT_TOKENS - instruction_overhead_tokens - estimate_tokens(query))

    selected_chunks = _select_and_trim_chunks(
        context_chunks, MAX_CONTEXT_CHUNKS, MAX_CHARS_PER_CHUNK, context_token_budget
    )

    chat_history = chat_history or []
    memory_lines = []
    for msg in chat_history[-8:]:
        role = msg.get("role", "user").title()
        content = " ".join((msg.get("content") or "").split())
        if content:
            memory_lines.append(f"{role}: {content[:700]}")
    memory_context = "\n".join(memory_lines) if memory_lines else "No previous chat context."

    def build_prompt(chunks):
        context_str = ""
        for chunk in chunks:
            filename = chunk.get("filename", "Unknown")
            page_num = chunk.get("page_number", 1)
            content_type = chunk.get("content_type", "text")
            text_content = chunk.get("text_content", "")
            context_str += f"--- SOURCE [{filename}, Page {page_num}, Type: {content_type}] ---\n{text_content}\n\n"

        return f"""You are a precise Document Intelligence Assistant. Answer the user's question using ONLY the exact content in the sources below.

Rules:
- Use the previous chat context to resolve follow-up questions, pronouns, comparisons, and references to earlier documents or answers.
- The retrieved sources below are already limited to the user's selected scope. Do not answer from outside that scope.
- CRITICAL — source attribution: every source block below is labelled with its exact filename in the header line `--- SOURCE [filename, Page N] ---`. When you cite or describe information, you MUST use that exact filename. Never substitute a company name, product name, or any other label for the filename. If the data came from `Company_report.pdf`, cite `Company_report.pdf` — not "Zephyr Consulting" or any other name mentioned inside the text.
- For numerical queries (sum, average, total of salaries/values across multiple people): extract every relevant number from the sources, show each value with its source person/row, then compute the result step by step. If a person is not found in any source, say so explicitly rather than omitting them silently.
- Read the sources for their meaning and synthesize a direct, contextual answer in your own words. Do not just locate matching keywords or quote verbatim unless a precise quote is genuinely needed.
- Cite a source with [filename, Page X] only next to the specific claim it supports. Cite EACH distinct source at most once in the whole answer, and only the sources you actually relied on. Do not cite every sentence and do not pad the answer with unused sources.
- If a source chunk is a markdown table and the user asks for tabular information, preserve the answer as a clean markdown table.
- If the answer depends on an image-description chunk, say what the image shows and cite it.
- If the question asks for a specific field/value from a table, provide only the needed value plus brief context.
- If the sources genuinely do not contain the answer, say so plainly instead of guessing or citing irrelevant sources.
- Keep formatting clean: short paragraphs, markdown bullets for lists, markdown tables for table answers. Be concise.

Context sources:
{context_str}

Previous chat context:
{memory_context}

User Question: {query}
Contextual Answer:"""

    prompt = build_prompt(selected_chunks)

    try:
        print(f"[Groq] Sending RAG prompt ({len(selected_chunks)} chunks, ~{estimate_tokens(prompt)} tokens)...", flush=True)
        _groq_start = time.time()
        client = get_client()
        response = client.chat.completions.create(
            model=MODEL,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=MAX_COMPLETION_TOKENS,
        )
        print(f"[Groq] Response received in {time.time() - _groq_start:.1f}s", flush=True)
        return response.choices[0].message.content
    except Exception as e:
        print(f"[Groq] Call FAILED after {time.time() - _groq_start:.1f}s: {e}", flush=True)
        err_text = str(e)
        # If we still somehow overshoot the token-per-minute limit, retry once with a
        # much smaller context instead of failing outright.
        if "413" in err_text or "rate_limit_exceeded" in err_text or "Request too large" in err_text:
            logger.warning("Groq request too large, retrying with a trimmed context: %s", err_text)
            try:
                time.sleep(1)
                smaller_chunks = _select_and_trim_chunks(
                    context_chunks, max_chunks=2, max_chars_per_chunk=400, token_budget=900
                )
                retry_prompt = build_prompt(smaller_chunks)
                client = get_client()
                response = client.chat.completions.create(
                    model=MODEL,
                    messages=[{"role": "user", "content": retry_prompt}],
                    max_tokens=600,
                )
                return response.choices[0].message.content
            except Exception as retry_exc:
                logger.error(f"Groq retry after 413 also failed: {str(retry_exc)}")
                return "The documents matched were too large to process in one go. Try asking a more specific question, or narrow the scope to a single document/folder."
        logger.error(f"Groq API error during Q&A: {str(e)}")
        return f"Error communicating with Groq: {str(e)}"


def ask_multimodal_video(file_path: str, query: str, transcript_text: str = "") -> str:
    filename = os.path.basename(file_path)
    if not is_valid_api_key():
        return (
            f"Video '{filename}' is registered, but no valid GROQ_API_KEY is set, "
            "so I can't generate an answer right now."
        )

    available_text = (transcript_text or "").strip()
    if not available_text:
        return (
            f"I can't directly watch '{filename}' frame-by-frame — this app answers video questions "
            "from its transcript/metadata text, and none was available for this file. "
            "If this is meant to have spoken content, check that transcription succeeded for it."
        )

    try:
        client = get_client()
        prompt = f"""You are answering a question about a video using its transcript/metadata text below.
Answer the user's question directly and contextually based on the meaning of the transcript, not by quoting it verbatim.
If the transcript doesn't contain enough information to answer, say so plainly.

Transcript/metadata:
{available_text[:6000]}

Question: {query}
Answer:"""
        response = client.chat.completions.create(
            model=MODEL,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=MAX_COMPLETION_TOKENS,
        )
        return response.choices[0].message.content
    except Exception as e:
        logger.error(f"Groq API error during video Q&A: {str(e)}")
        return f"Error communicating with Groq: {str(e)}"


def generate_summary(text_content: str, summary_type: str = "short") -> str:
    if not is_valid_api_key():
        sentences = [s.strip() for s in text_content.split(".") if s.strip()]
        if summary_type == "pointers":
            return "\n".join([f"- {s}." for s in sentences[:5]])
        if summary_type == "detailed":
            return " ".join(sentences[:10]) + "."
        return " ".join(sentences[:3]) + "."

    def build_summary_prompt(text, char_limit):
        lang_instruction = "Always write your response in English, regardless of the language of the source text."
        if summary_type == "detailed":
            return f"{lang_instruction}\n\nProvide a detailed, structured summary of the following document. Preserve important tables, figures, metrics, and named entities when present:\n\n{text[:char_limit]}"
        if summary_type == "pointers":
            return f"{lang_instruction}\n\nSummarize the following document as clean markdown bullets with key takeaways, decisions, numbers, and risks:\n\n{text[:char_limit]}"
        return f"{lang_instruction}\n\nProvide a short summary in maximum 3 sentences highlighting the core message of the document:\n\n{text[:min(char_limit, 3500)]}"

    try:
        client = get_client()
        prompt = build_summary_prompt(text_content, 7000)
        response = client.chat.completions.create(
            model=MODEL,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=700,
        )
        return response.choices[0].message.content
    except Exception as e:
        err_text = str(e)
        if "413" in err_text or "rate_limit_exceeded" in err_text or "Request too large" in err_text:
            logger.warning("Groq summary request too large, retrying with shorter input: %s", err_text)
            try:
                time.sleep(1)
                client = get_client()
                retry_prompt = build_summary_prompt(text_content, 2000)
                response = client.chat.completions.create(
                    model=MODEL,
                    messages=[{"role": "user", "content": retry_prompt}],
                    max_tokens=500,
                )
                return response.choices[0].message.content
            except Exception as retry_exc:
                logger.error(f"Groq retry after 413 also failed during summarization: {str(retry_exc)}")
                return "This document was too large to summarize in one pass. Try again in a moment."
        logger.error(f"Groq API error during summarization: {str(e)}")
        return f"Error generating summary: {str(e)}"

def _needs_query_rewrite(query_text: str, search_mode: str) -> bool:
    """Only pay for an LLM rewrite call when literal-matching retrieval paths
    are actually in play. Semantic/KNN search already generalizes via
    embeddings, so a rewrite adds cost with no benefit there. Short queries
    (1-2 words) are also low-risk for plural/synonym mismatches."""
    if search_mode == "semantic":
        return False
    word_count = len(query_text.strip().split())
    return word_count >= 3

def rewrite_query_for_retrieval(query_text: str, search_mode: str = "keyword") -> str:
    """Ask the LLM to restate the query using likely document vocabulary
    (singular forms, standard report terminology) before it hits keyword/local
    retrieval — those paths only do literal text matching and don't understand
    that 'margins' means the same thing as 'margin'."""
    if not _needs_query_rewrite(query_text, search_mode) or not is_valid_api_key():
        return query_text
    try:
        print(f"[Groq] Rewriting query for retrieval...", flush=True)
        _rw_start = time.time()
        client = get_client()
        prompt = f"""Rewrite the following question into 3-6 short keyword phrases
likely to appear verbatim in a corporate report (use singular forms, standard
business report terminology, no question words). Output ONLY the phrases,
space-separated, no punctuation, no explanation.

Question: {query_text}
Phrases:"""
        response = client.chat.completions.create(
            model=MODEL,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=40,
        )
        rewritten = response.choices[0].message.content.strip()
        print(f"[Groq] Query rewrite done in {time.time() - _rw_start:.1f}s", flush=True)
        return f"{query_text} {rewritten}" if rewritten else query_text
    except Exception as e:
        print(f"[Groq] Query rewrite FAILED: {e}", flush=True)
        logger.warning("Query rewrite failed, falling back to original query: %s", str(e))
        return query_text